fix: Pin pytest version When using pytest-8.2.0 with async-0.21.1, func tests throw an error:
`AttributeError: 'FixtureDef' object has no attribute 'unittest'`

Refer: https://github.com/charmed-kubernetes/pytest-operator/issues/131

Therefore, the pytest version is pinned till the issue is resolved
upstream.